name: drake_eq2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.23
  - scipy>=1.9
  - matplotlib>=3.6
  - pandas>=1.5
  - seaborn>=0.12
  - jupyter
  - notebook
  - pyyaml
  - pip
  - pip:
    - scikit-learn>=1.2  # For Sobol indices calculation
